"""empty message

Revision ID: 933714c025da
Revises: 
Create Date: 2020-05-04 22:31:54.498388

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '933714c025da'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('password_hash', sa.String(length=200), nullable=True),
    sa.Column('created_on', sa.DateTime(), nullable=True),
    sa.Column('last_login', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('address',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('line_one', sa.String(length=50), nullable=False),
    sa.Column('line_two', sa.String(length=50), nullable=True),
    sa.Column('line_three', sa.String(length=50), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('education',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('school', sa.String(length=50), nullable=False),
    sa.Column('location', sa.String(length=50), nullable=True),
    sa.Column('degree_and_field', sa.String(length=50), nullable=True),
    sa.Column('date_from', sa.String(length=7), nullable=False),
    sa.Column('date_to', sa.String(length=7), nullable=True),
    sa.Column('gpa', sa.String(length=20), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('profile',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=50), nullable=True),
    sa.Column('last_name', sa.String(length=50), nullable=True),
    sa.Column('email', sa.String(length=50), nullable=True),
    sa.Column('phone_number', sa.String(length=50), nullable=True),
    sa.Column('website_url', sa.String(length=50), nullable=True),
    sa.Column('github_url', sa.String(length=50), nullable=True),
    sa.Column('linkedin_url', sa.String(length=50), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('profile')
    op.drop_table('education')
    op.drop_table('address')
    op.drop_table('user')
    # ### end Alembic commands ###
