"""empty message

Revision ID: d35513f95fae
Revises: 2b7d847f0a24
Create Date: 2020-05-13 02:29:56.483960

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd35513f95fae'
down_revision = '2b7d847f0a24'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('personal_project_job_relationship_table',
    sa.Column('job_id', sa.Integer(), nullable=False),
    sa.Column('personal_project_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['job.id'], ),
    sa.ForeignKeyConstraint(['personal_project_id'], ['personal_project.id'], ),
    sa.PrimaryKeyConstraint('job_id', 'personal_project_id')
    )
    op.create_table('skill_job_relationship_table',
    sa.Column('job_id', sa.Integer(), nullable=False),
    sa.Column('skill_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['job.id'], ),
    sa.ForeignKeyConstraint(['skill_id'], ['skill.id'], ),
    sa.PrimaryKeyConstraint('job_id', 'skill_id')
    )
    op.create_table('work_experience_job_relationship_table',
    sa.Column('job_id', sa.Integer(), nullable=False),
    sa.Column('work_experience_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['job.id'], ),
    sa.ForeignKeyConstraint(['work_experience_id'], ['work_experience.id'], ),
    sa.PrimaryKeyConstraint('job_id', 'work_experience_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('work_experience_job_relationship_table')
    op.drop_table('skill_job_relationship_table')
    op.drop_table('personal_project_job_relationship_table')
    # ### end Alembic commands ###
